---
name: blood_hub
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  lottie: ^0.6.0
  google_fonts: ^1.1.0
  modal_bottom_sheet: ^0.2.2
  flutter_onboard: ^0.1.0
  font_awesome_flutter: ^8.8.1
  shimmer: ^1.1.1
  provider: ^4.3.2+2
  flutter_screenutil: ^3.1.1
  share: ^0.6.5+3
  shared_preferences: ^0.5.12+2
  lite_rolling_switch: ^0.1.1
  custom_sheet: ^0.1.1+4
  get: ^3.13.2
  floaty_head: ^1.1.0
  quick_actions: ^0.4.0+10
  flutter_svg: ^0.19.0
  image_picker: ^0.6.7+12
  animated_bottom_navigation_bar: ^0.1.2+2
  rubber: ^0.4.0
  circular_reveal_animation: ^1.1.5
  bubble_tab_indicator: ^0.1.4
  custom_navigation_bar: ^0.3.2
  fluttertoast: ^7.1.1
  ai_awesome_message: ^0.3.0
  flutter_animation_progress_bar: ^1.0.5
  map: ^0.1.0+1
  geocoder: null
  latlng: null
  gps: null
  flutter_automation: null
  flutter_open_whatsapp: null
  razorpay_flutter: 1.2.2
  step_progress_indicator: null
  flutter_linkify: null
  flutter_easyrefresh: null
  dio: null
  connectivity: null
  cached_network_image: null
  flutter_local_notifications: null
  webview_flutter: null
  retrofit: null
  intl: ^0.15.8
  datetime_picker_formfield: null
  convex_bottom_bar: ^2.1.1
  simple_animations: ^1.3.3
  flutter_rating_bar: ^3.0.1+1
  firebase_core: null
  firebase_auth: null
  firebase_database: null
  firebase_analytics: ^6.0.2
  firebase_storage: ^4.0.1
  firebase_messaging: ^7.0.3
  firebase_dynamic_links: ^0.6.0+2
  url_launcher: any
  bubble_bottom_bar: ^1.2.0
  in_app_review: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: null
  pedantic: ^1.8.0
  flutter_native_splash: ^0.1.9
flutter_native_splash:
  image: assets/images/splash.png
  color: E11E3C
  android_disable_fullscreen: false
flutter:
  uses-material-design: true
  assets:
  - assets/lottie/
  - assets/images/
